### ISSUE TITLE
Max inactive interval ignored

### ISSUE THREAD

**Issue by awesomekosm** [micronaut-projects/micronaut-redis#209]
### Expected Behavior

When logging and and browsing around, it is unexpected to be logged out. So the time out does not seem to be extended when the browser sends the cookie with an active session.

### Actual Behaviour

User is redirected to login page when browsing around.

### Steps To Reproduce

```yml
redis:
  health:
    enabled: false #disabled to prevent /health spam ddos
  uri: redis://redis
  port: 6379

micronaut:
  session:
    max-inactive-interval: PT1M
    http:
      redis:
        enabled: true
        # The Redis namespace to write sessions to
        namespace: 'app:sessions'
        # Write session changes in the background
        write-mode: BACKGROUND
        # Disable programmatic activation of keyspace events
        enable-keyspace-events: false
        valueSerializer: io.micronaut.jackson.serialize.JacksonObjectSerializer
```
Login, keep refreshing the page, get sent back to login.

### Environment Information

openjdk:11-jre-slim container
ubuntu 20.04.2 + openjdk-16.0.1

### Version

2.5.9
