### ISSUE TITLE
Allow Redis to be disabled via configuration (prevent DefaultRedisConfiguration from loading)

### ISSUE THREAD

**Issue by matt-snider** [micronaut-projects/micronaut-redis#352]
### Feature description

I am using Redis for caching and trying to get my tests to run without a running Redis instance. The test cases do not actually require Redis and I can swap out the `SyncCache<?>` being injected with either Caffeine or No Op Cache as describe [in the documentation](https://micronaut-projects.github.io/micronaut-cache/snapshot/guide/index.html).

However, I haven't found a way to disable the `DefaultRedisConfiguration` from loading in the tests and it seems to do so no matter what I set the `application-test.yml` config to. For example `redis: null` has no effect. Upon loading, it complains about `uri` not being set.

I think this is because `@Requires(property = RedisSetting.PREFIX)` does not require that the property has a value, just that it is there.

Could you consider having an additional rule like `@Requires(property = RedisSetting.ENABLED,  notEquals = "false")` so that `redis.enabled: false` would provide the functionality I am looking for?

**Comment by donbeave** [comment]
We are using it in a different manner. We have a configuration like this:

```yaml
redis:
  servers:
    lock:
      uri: ${LOCK_REDIS_URL:`redis://localhost:6379`}
```

Where we use a dedicated Redis instance for distributed locks among our microservices. We would like to have an option to opt-out primary (default) redis, as we don't expect it will configure automatically when we didn't set it explicitly.

Probably the suggested idea of adding `redis.enabled: false` would be fine for our case. But I personally think it's a bit confusing, as it looks like it disables the whole Redis feature. So maybe something like `redis.primary-enabled: false` would be better.

Frankly say, for Micronaut 5 it will be better to use a similar approach as other Micronaut modules are using:

```
datasources:
  default:
    url: jdbc:postgresql://primary-postgresql:5432/db
    // all default configuration for primary one

jooq:
  datasources:
    default:
      sql-dialect: POSTGRES
      // all default configuration for primary one

flyway:
  datasources:
    default:
      enabled: true
      // all default configuration for primary one

# suggested changes for the Redis module
redis:
  default:
    enabled: true
    uri: redis://primary-redis:6379
  lock:
    enabled: true
    uri: redis://lock-redis:6379
```

With such approach I think it will solve this issue and also make it consistent across Micronaut configurations.

@graemerocher @sdelamo what do you think? I can make a PR for both cases, one for the current (4.x) with adding a property to toggle this behavior and make a broken change for the next major release.
