### ISSUE TITLE
[bug] Multiple Redis Connections

### ISSUE THREAD

**Issue by zhenchuan** [micronaut-projects/micronaut-redis#5]
when setting multiple redis servers , it always connect to `localhost:6379` by default, the config has no effect at all !
```
redis:
    servers:
        foo:
            uri: redis://foo:1223
        bar:
            uri: redis://bar:4567
```
